// AUTO-GENERATED by api/scripts/generate-n8n-app.ts. Do not edit by hand.
// Run `pnpm --filter api run generate:n8n` to regenerate.
/* eslint-disable */
import {
	NodeConnectionTypes,
	type IHookFunctions,
	type INodeType,
	type INodeTypeDescription,
	type IWebhookFunctions,
	type IWebhookResponseData,
} from "n8n-workflow";

const WEBHOOKS_URL = "https://api.videogen.io/v1/webhooks/endpoints";

const EVENT_OPTIONS = [
  {
    "name": "file.download_ready",
    "value": "file.download_ready",
    "description": "Triggers when a file is ready to download."
  },
  {
    "name": "file.playback_ready",
    "value": "file.playback_ready",
    "description": "Triggers when a file is ready for playback."
  },
  {
    "name": "file.upload.completed",
    "value": "file.upload.completed",
    "description": "Triggers when a file upload completes."
  },
  {
    "name": "project_export.failed",
    "value": "project_export.failed",
    "description": "Triggers when a project export fails."
  },
  {
    "name": "project_export.succeeded",
    "value": "project_export.succeeded",
    "description": "Triggers when a project export completes successfully."
  },
  {
    "name": "tool_execution.failed",
    "value": "tool_execution.failed",
    "description": "Triggers when a tool execution fails."
  },
  {
    "name": "tool_execution.succeeded",
    "value": "tool_execution.succeeded",
    "description": "Triggers when a tool execution completes successfully."
  },
  {
    "name": "workflow_run.failed",
    "value": "workflow_run.failed",
    "description": "Triggers when a workflow run fails."
  },
  {
    "name": "workflow_run.succeeded",
    "value": "workflow_run.succeeded",
    "description": "Triggers when a workflow run completes successfully."
  }
];

const credentialTypeFor = (authentication: string): string =>
	authentication === "apiKey" ? "videoGenApi" : "videoGenOAuth2Api";

export class VideoGenTrigger implements INodeType {
	description: INodeTypeDescription = {
		displayName: "VideoGen Trigger",
		name: "videoGenTrigger",
		icon: {
			light: "file:videogen.svg",
			dark: "file:videogen.dark.svg",
		},
		group: ["trigger"],
		version: 1,
		subtitle: '={{($parameter["events"] || []).join(", ")}}',
		description: "Starts the workflow when VideoGen sends a subscribed event",
		defaults: { name: "VideoGen Trigger" },
		inputs: [],
		outputs: [NodeConnectionTypes.Main],
		credentials: [
			{
				name: "videoGenOAuth2Api",
				required: true,
				displayOptions: { show: { authentication: ["oAuth2"] } },
			},
			{
				name: "videoGenApi",
				required: true,
				displayOptions: { show: { authentication: ["apiKey"] } },
			},
		],
		webhooks: [
			{ name: "default", httpMethod: "POST", responseMode: "onReceived", path: "webhook" },
		],
		properties: [
			{
				displayName: "Authentication",
				name: "authentication",
				type: "options",
				noDataExpression: true,
				options: [
					{ name: "OAuth2 (Sign in with VideoGen)", value: "oAuth2" },
					{ name: "API Key", value: "apiKey" },
				],
				default: "oAuth2",
			},
			{
				displayName: "Events",
				name: "events",
				type: "multiOptions",
				required: true,
				default: [],
				options: EVENT_OPTIONS,
				description: "The VideoGen events that start this workflow",
			},
		],
	};

	webhookMethods = {
		default: {
			async checkExists(this: IHookFunctions): Promise<boolean> {
				const staticData = this.getWorkflowStaticData("node");
				return typeof staticData.endpointId === "string";
			},

			async create(this: IHookFunctions): Promise<boolean> {
				const authentication = this.getNodeParameter("authentication") as string;
				const events = this.getNodeParameter("events") as string[];
				const webhookUrl = this.getNodeWebhookUrl("default");

				const response = (await this.helpers.httpRequestWithAuthentication.call(
					this,
					credentialTypeFor(authentication),
					{
						method: "POST",
						url: WEBHOOKS_URL,
						headers: { "X-VideoGen-Client": "n8n" },
						body: { url: webhookUrl, events, description: "n8n webhook subscription" },
						json: true,
					},
				)) as { endpointId?: string };

				if (response.endpointId == null) {
					return false;
				}

				const staticData = this.getWorkflowStaticData("node");
				staticData.endpointId = response.endpointId;
				return true;
			},

			async delete(this: IHookFunctions): Promise<boolean> {
				const staticData = this.getWorkflowStaticData("node");
				const endpointId = staticData.endpointId;
				if (typeof endpointId !== "string") {
					return true;
				}

				const authentication = this.getNodeParameter("authentication") as string;
				try {
					await this.helpers.httpRequestWithAuthentication.call(
						this,
						credentialTypeFor(authentication),
						{
							method: "DELETE",
							url: `${WEBHOOKS_URL}/${endpointId}`,
							headers: { "X-VideoGen-Client": "n8n" },
							json: true,
						},
					);
				} catch (error: unknown) {
					const message = error instanceof Error ? error.message : String(error);
					this.logger.warn("VideoGen webhook delete failed; treating as already gone.", {
						error: message,
					});
				}

				delete staticData.endpointId;
				return true;
			},
		},
	};

	async webhook(this: IWebhookFunctions): Promise<IWebhookResponseData> {
		const body = this.getBodyData();
		return { workflowData: [this.helpers.returnJsonArray(body)] };
	}
}
