// AUTO-GENERATED by api/scripts/generate-n8n-app.ts. Do not edit by hand.
// Run `pnpm --filter api run generate:n8n` to regenerate.
/* eslint-disable */
import { NodeApiError, NodeConnectionTypes, type IDataObject, type IExecuteFunctions, type IHttpRequestMethods, type INodeExecutionData, type INodeType, type INodeTypeDescription } from "n8n-workflow";

const BASE_URL = "https://api.videogen.io";
const POLL_INTERVAL_MS = 5000;
const POLL_TIMEOUT_MS = 3600000;
const WORKFLOW_STARTS: Record<string, { method: IHttpRequestMethods; path: string; jsonKeys: string[]; requiredBodyKeys: string[] }> = {
  "promptToVideoClip": {
    "method": "POST",
    "path": "/v1/workflows/prompt-to-video-clip",
    "jsonKeys": [
      "imageFileIds",
      "aspectRatio",
      "exportOptions"
    ],
    "requiredBodyKeys": [
      "prompt"
    ]
  },
  "scriptToVideo": {
    "method": "POST",
    "path": "/v1/workflows/script-to-video",
    "jsonKeys": [
      "aspectRatio",
      "visualStyle",
      "featuredBRollFileIds",
      "scenes",
      "remixActions",
      "exportOptions"
    ],
    "requiredBodyKeys": [
      "script",
      "visualStyle"
    ]
  },
  "slideshowToVideo": {
    "method": "POST",
    "path": "/v1/workflows/slideshow-to-video",
    "jsonKeys": [
      "slideScripts",
      "aspectRatio",
      "captionStyle",
      "remixActions",
      "exportOptions"
    ],
    "requiredBodyKeys": [
      "fileId"
    ]
  },
  "voiceoverToVideo": {
    "method": "POST",
    "path": "/v1/workflows/voiceover-to-video",
    "jsonKeys": [
      "scenes",
      "aspectRatio",
      "visualStyle",
      "captionStyle",
      "remixActions",
      "exportOptions"
    ],
    "requiredBodyKeys": [
      "fileId",
      "visualStyle"
    ]
  }
};

const credentialTypeFor = (authentication: string): string =>
	authentication === "oAuth2" ? "videoGenOAuth2Api" : "videoGenApi";

const sleep = async (ms: number): Promise<void> =>
	new Promise((resolve) => {
		const timeout = globalThis.setTimeout;
		timeout(resolve, ms);
	});

const parseMaybeJson = (value: unknown, key: string, jsonKeys: string[]): unknown => {
	if (!jsonKeys.includes(key) || typeof value !== "string") {
		return value;
	}
	const trimmed = value.trim();
	if (trimmed === "") {
		return undefined;
	}
	return JSON.parse(trimmed);
};

const pollWorkflowRun = async (
	ctx: IExecuteFunctions,
	credentialType: string,
	workflowRunId: string,
): Promise<IDataObject> => {
	const startedAt = Date.now();
	for (;;) {
		const run = (await ctx.helpers.httpRequestWithAuthentication.call(ctx, credentialType, {
			method: "GET",
			url: `${BASE_URL}/v1/workflows/runs/${encodeURIComponent(workflowRunId)}`,
			json: true,
		})) as IDataObject;
		const status = run.status;
		if (status === "succeeded" || status === "failed" || status === "cancelled") {
			if (status !== "succeeded") {
				const error = run.error;
				const message =
					error != null && typeof error === "object" && "message" in error
						? String(Reflect.get(error, "message"))
						: `Workflow run ${String(status)}`;
				throw new NodeApiError(ctx.getNode(), { message });
			}
			return run;
		}
		if (Date.now() - startedAt > POLL_TIMEOUT_MS) {
			throw new NodeApiError(ctx.getNode(), { message: "Timed out waiting for workflow run" });
		}
		await sleep(POLL_INTERVAL_MS);
	}
};

export class VideoGen implements INodeType {
	description: INodeTypeDescription = {
		displayName: "VideoGen",
		name: "videoGen",
		icon: {
			light: "file:videogen.svg",
			dark: "file:videogen.dark.svg",
		},
		group: ["transform"],
		version: 1,
		subtitle: '={{$parameter["operation"] + ": " + $parameter["resource"]}}',
		description: "Start VideoGen workflows and wait until the exported MP4 is ready",
		defaults: { name: "VideoGen" },
		inputs: [NodeConnectionTypes.Main],
		outputs: [NodeConnectionTypes.Main],
		usableAsTool: true,
		credentials: [
		  {
		    "name": "videoGenOAuth2Api",
		    "required": true,
		    "displayOptions": {
		      "show": {
		        "authentication": [
		          "oAuth2"
		        ]
		      }
		    }
		  },
		  {
		    "name": "videoGenApi",
		    "required": true,
		    "displayOptions": {
		      "show": {
		        "authentication": [
		          "apiKey"
		        ]
		      }
		    }
		  }
		],
		requestDefaults: {
		  "baseURL": "https://api.videogen.io",
		  "headers": {
		    "Accept": "application/json",
		    "Content-Type": "application/json",
		    "X-VideoGen-Client": "n8n"
		  }
		},
		properties: [
		  {
		    "displayName": "Authentication",
		    "name": "authentication",
		    "type": "options",
		    "noDataExpression": true,
		    "options": [
		      {
		        "name": "OAuth2 (Sign in with VideoGen)",
		        "value": "oAuth2"
		      },
		      {
		        "name": "API Key",
		        "value": "apiKey"
		      }
		    ],
		    "default": "oAuth2"
		  },
		  {
		    "displayName": "Resource",
		    "name": "resource",
		    "type": "options",
		    "noDataExpression": true,
		    "options": [
		      {
		        "name": "Workflow",
		        "value": "workflow"
		      }
		    ],
		    "default": "workflow"
		  },
		  {
		    "displayName": "Operation",
		    "name": "operation",
		    "type": "options",
		    "noDataExpression": true,
		    "displayOptions": {
		      "show": {
		        "resource": [
		          "workflow"
		        ]
		      }
		    },
		    "options": [
		      {
		        "name": "Prompt to video clip",
		        "value": "promptToVideoClip",
		        "action": "Prompt to video clip",
		        "description": "Starts the workflow with auto-export on, waits until the video is ready, then returns the project id, editor link, signed MP4 download URL, and thumbnail URL.",
		        "routing": {
		          "request": {
		            "method": "POST",
		            "url": "/v1/workflows/prompt-to-video-clip"
		          }
		        }
		      },
		      {
		        "name": "Script to video",
		        "value": "scriptToVideo",
		        "action": "Script to video",
		        "description": "Starts the workflow with auto-export on, waits until the video is ready, then returns the project id, editor link, signed MP4 download URL, and thumbnail URL.",
		        "routing": {
		          "request": {
		            "method": "POST",
		            "url": "/v1/workflows/script-to-video"
		          }
		        }
		      },
		      {
		        "name": "Slideshow to video",
		        "value": "slideshowToVideo",
		        "action": "Slideshow to video",
		        "description": "Starts the workflow with auto-export on, waits until the video is ready, then returns the project id, editor link, signed MP4 download URL, and thumbnail URL.",
		        "routing": {
		          "request": {
		            "method": "POST",
		            "url": "/v1/workflows/slideshow-to-video"
		          }
		        }
		      },
		      {
		        "name": "Voiceover to video",
		        "value": "voiceoverToVideo",
		        "action": "Voiceover to video",
		        "description": "Starts the workflow with auto-export on, waits until the video is ready, then returns the project id, editor link, signed MP4 download URL, and thumbnail URL.",
		        "routing": {
		          "request": {
		            "method": "POST",
		            "url": "/v1/workflows/voiceover-to-video"
		          }
		        }
		      }
		    ],
		    "default": "promptToVideoClip"
		  },
		  {
		    "displayName": "Prompt",
		    "name": "prompt",
		    "type": "string",
		    "default": "",
		    "routing": {
		      "send": {
		        "type": "body",
		        "property": "prompt"
		      }
		    },
		    "required": true,
		    "description": "Text prompt describing the video to generate (e.g. `A golden retriever running through a sunlit meadow in slow motion, cinematic`).",
		    "displayOptions": {
		      "show": {
		        "resource": [
		          "workflow"
		        ],
		        "operation": [
		          "promptToVideoClip"
		        ]
		      }
		    }
		  },
		  {
		    "displayName": "Additional Fields",
		    "name": "additionalFields",
		    "type": "collection",
		    "placeholder": "Add Field",
		    "default": {},
		    "displayOptions": {
		      "show": {
		        "resource": [
		          "workflow"
		        ],
		        "operation": [
		          "promptToVideoClip"
		        ]
		      }
		    },
		    "options": [
		      {
		        "displayName": "Image File Ids",
		        "name": "imageFileIds",
		        "type": "json",
		        "default": "[]",
		        "routing": {
		          "send": {
		            "type": "body",
		            "property": "imageFileIds",
		            "value": "={{ $value ? JSON.parse($value) : undefined }}"
		          }
		        },
		        "description": "Optional ids of previously uploaded reference images (e.g. `vg_file_...`) that guide the opening frame. Upload files via `POST /v1/files/upload` first."
		      },
		      {
		        "displayName": "Duration Seconds",
		        "name": "durationSeconds",
		        "type": "number",
		        "default": 0,
		        "routing": {
		          "send": {
		            "type": "body",
		            "property": "durationSeconds"
		          }
		        },
		        "description": "Desired clip length in whole seconds (1 to 30). Defaults to 10. The generated clip is clamped to the selected quality's supported range."
		      },
		      {
		        "displayName": "Aspect Ratio",
		        "name": "aspectRatio",
		        "type": "json",
		        "default": "{}",
		        "routing": {
		          "send": {
		            "type": "body",
		            "property": "aspectRatio",
		            "value": "={{ $value ? JSON.parse($value) : undefined }}"
		          }
		        },
		        "description": "Aspect ratio as a width:height pair (e.g. 16 and 9 for 16:9). Not pixel dimensions."
		      },
		      {
		        "displayName": "Quality",
		        "name": "quality",
		        "type": "options",
		        "default": "LOW",
		        "routing": {
		          "send": {
		            "type": "body",
		            "property": "quality"
		          }
		        },
		        "options": [
		          {
		            "name": "LOW",
		            "value": "LOW"
		          },
		          {
		            "name": "STANDARD",
		            "value": "STANDARD"
		          },
		          {
		            "name": "HIGH",
		            "value": "HIGH"
		          },
		          {
		            "name": "MAX",
		            "value": "MAX"
		          }
		        ],
		        "description": "Video generation quality tier (`LOW`, `STANDARD`, `HIGH`, or `MAX`). Also used for the opening-frame image. Optional; when omitted, your account's Default AI quality for video is used (change it at https://app.videogen.io/settings/account)."
		      },
		      {
		        "displayName": "Is Output Temporary",
		        "name": "isOutputTemporary",
		        "type": "boolean",
		        "default": false,
		        "routing": {
		          "send": {
		            "type": "body",
		            "property": "isOutputTemporary"
		          }
		        },
		        "description": "When true, the generated OUTPUT files (the opening-frame image and the video clip) are created as temporary: guaranteed available for 24 hours, after which they may be archived and later deleted. Use this when your integration downloads or re-hosts the results itself and does not need VideoGen to retain them. The project and its metadata are unaffected. Defaults to false."
		      },
		      {
		        "displayName": "Hide From Ui",
		        "name": "hideFromUi",
		        "type": "boolean",
		        "default": false,
		        "routing": {
		          "send": {
		            "type": "body",
		            "property": "hideFromUi"
		          }
		        },
		        "description": "When true, the project is hidden from Home and Projects by default, and generated files are hidden from the Media page. The project and files remain accessible through the API. Defaults to false."
		      },
		      {
		        "displayName": "Export Options",
		        "name": "exportOptions",
		        "type": "json",
		        "default": "{}",
		        "routing": {
		          "send": {
		            "type": "body",
		            "property": "exportOptions",
		            "value": "={{ $value ? JSON.parse($value) : undefined }}"
		          }
		        },
		        "description": "Export settings used when `autoExport` is true. Ignored when `autoExport` is false. Omitted fields use the same defaults as `POST /v1/projects/{projectId}/export`."
		      }
		    ]
		  },
		  {
		    "displayName": "Script",
		    "name": "script",
		    "type": "string",
		    "default": "",
		    "routing": {
		      "send": {
		        "type": "body",
		        "property": "script"
		      }
		    },
		    "required": true,
		    "description": "The narration script, used verbatim. This exact text is narrated and turned into a video — it is not rewritten or expanded.",
		    "displayOptions": {
		      "show": {
		        "resource": [
		          "workflow"
		        ],
		        "operation": [
		          "scriptToVideo"
		        ]
		      }
		    }
		  },
		  {
		    "displayName": "Visual Style",
		    "name": "visualStyle",
		    "type": "json",
		    "default": "{}",
		    "routing": {
		      "send": {
		        "type": "body",
		        "property": "visualStyle",
		        "value": "={{ $value ? JSON.parse($value) : undefined }}"
		      }
		    },
		    "required": true,
		    "description": "Visual style for the generated b-roll.",
		    "displayOptions": {
		      "show": {
		        "resource": [
		          "workflow"
		        ],
		        "operation": [
		          "scriptToVideo"
		        ]
		      }
		    }
		  },
		  {
		    "displayName": "Additional Fields",
		    "name": "additionalFields",
		    "type": "collection",
		    "placeholder": "Add Field",
		    "default": {},
		    "displayOptions": {
		      "show": {
		        "resource": [
		          "workflow"
		        ],
		        "operation": [
		          "scriptToVideo"
		        ]
		      }
		    },
		    "options": [
		      {
		        "displayName": "Aspect Ratio",
		        "name": "aspectRatio",
		        "type": "json",
		        "default": "{}",
		        "routing": {
		          "send": {
		            "type": "body",
		            "property": "aspectRatio",
		            "value": "={{ $value ? JSON.parse($value) : undefined }}"
		          }
		        },
		        "description": "Aspect ratio as a width:height pair (e.g. 16 and 9 for 16:9). Not pixel dimensions."
		      },
		      {
		        "displayName": "Visual Pacing",
		        "name": "visualPacing",
		        "type": "options",
		        "default": "MEDIUM",
		        "routing": {
		          "send": {
		            "type": "body",
		            "property": "visualPacing"
		          }
		        },
		        "options": [
		          {
		            "name": "FAST",
		            "value": "FAST"
		          },
		          {
		            "name": "MEDIUM",
		            "value": "MEDIUM"
		          },
		          {
		            "name": "SLOW",
		            "value": "SLOW"
		          }
		        ],
		        "description": "How quickly visuals change. FAST shows more, shorter shots; SLOW holds each visual longer. Defaults to MEDIUM."
		      },
		      {
		        "displayName": "Quality",
		        "name": "quality",
		        "type": "options",
		        "default": "LOW",
		        "routing": {
		          "send": {
		            "type": "body",
		            "property": "quality"
		          }
		        },
		        "options": [
		          {
		            "name": "LOW",
		            "value": "LOW"
		          },
		          {
		            "name": "STANDARD",
		            "value": "STANDARD"
		          },
		          {
		            "name": "HIGH",
		            "value": "HIGH"
		          },
		          {
		            "name": "MAX",
		            "value": "MAX"
		          }
		        ],
		        "description": "Image generation quality tier for AI-generated visuals. Optional; when omitted, your account's Default AI quality for images is used (change it at https://app.videogen.io/settings/account). Only applies when `visualStyle.type` is AI_IMAGE; STOCK pulls existing footage and is unaffected."
		      },
		      {
		        "displayName": "Language",
		        "name": "language",
		        "type": "string",
		        "default": "",
		        "routing": {
		          "send": {
		            "type": "body",
		            "property": "language"
		          }
		        },
		        "description": "Output language as a BCP-47 code (e.g. `en`, `es`, `fr`). Defaults to English."
		      },
		      {
		        "displayName": "Voice Id",
		        "name": "voiceId",
		        "type": "string",
		        "default": "",
		        "routing": {
		          "send": {
		            "type": "body",
		            "property": "voiceId"
		          }
		        },
		        "description": "Catalog `displayName` (e.g. `Matilda`) or voice id from `GET /v1/resources/tts-voices` (e.g. `vg_voic_...`). A default voice is used when omitted. Any voice may be used here, including voices where `supportsDirectToolExecution` is false."
		      },
		      {
		        "displayName": "Voice Speed",
		        "name": "voiceSpeed",
		        "type": "number",
		        "default": 0,
		        "routing": {
		          "send": {
		            "type": "body",
		            "property": "voiceSpeed"
		          }
		        },
		        "description": "Speech rate multiplier, between 0.5 (half speed) and 2 (double speed). Defaults to the voice's default speed."
		      },
		      {
		        "displayName": "Actor Entity Id",
		        "name": "actorEntityId",
		        "type": "string",
		        "default": "",
		        "routing": {
		          "send": {
		            "type": "body",
		            "property": "actorEntityId"
		          }
		        },
		        "description": "Recommended. Optional id of a built-in stock actor or an ACTOR entity (e.g. `vg_enti_...`) with an image reference. When set, narration is delivered by that actor avatar. Omit or pass `null` for voiceover without an avatar."
		      },
		      {
		        "displayName": "Avatar Quality",
		        "name": "avatarQuality",
		        "type": "options",
		        "default": "LOW",
		        "routing": {
		          "send": {
		            "type": "body",
		            "property": "avatarQuality"
		          }
		        },
		        "options": [
		          {
		            "name": "LOW",
		            "value": "LOW"
		          },
		          {
		            "name": "STANDARD",
		            "value": "STANDARD"
		          },
		          {
		            "name": "HIGH",
		            "value": "HIGH"
		          },
		          {
		            "name": "MAX",
		            "value": "MAX"
		          }
		        ],
		        "description": "Avatar generation quality tier. Applies when `actorEntityId` is provided. Optional; when omitted, your account's Default AI quality for avatars is used."
		      },
		      {
		        "displayName": "Featured BRoll File Ids",
		        "name": "featuredBRollFileIds",
		        "type": "json",
		        "default": "[]",
		        "routing": {
		          "send": {
		            "type": "body",
		            "property": "featuredBRollFileIds",
		            "value": "={{ $value ? JSON.parse($value) : undefined }}"
		          }
		        },
		        "description": "Optional file ids of images or videos to feature as b-roll (e.g. `[\"vg_file_...\"]`). Upload files first via `POST /v1/files/upload`. Only image and video files are accepted."
		      },
		      {
		        "displayName": "Workflow Agent Context",
		        "name": "workflowAgentContext",
		        "type": "string",
		        "default": "",
		        "routing": {
		          "send": {
		            "type": "body",
		            "property": "workflowAgentContext"
		          }
		        },
		        "description": "Optional production notes for the AI that builds the video — visual direction that should not appear in the spoken narration (e.g. on-screen code or text to display, specific b-roll to feature, or scene-by-scene staging). Never spoken; keep the narration itself in `script`."
		      },
		      {
		        "displayName": "Scenes",
		        "name": "scenes",
		        "type": "json",
		        "default": "[]",
		        "routing": {
		          "send": {
		            "type": "body",
		            "property": "scenes",
		            "value": "={{ $value ? JSON.parse($value) : undefined }}"
		          }
		        },
		        "description": "Optional timed scene descriptions guiding what to show on screen during each absolute time range of the video. Ranges must be sorted by `startSeconds` and non-overlapping. Omit to let the workflow choose visuals automatically."
		      },
		      {
		        "displayName": "Remix Actions",
		        "name": "remixActions",
		        "type": "json",
		        "default": "[]",
		        "routing": {
		          "send": {
		            "type": "body",
		            "property": "remixActions",
		            "value": "={{ $value ? JSON.parse($value) : undefined }}"
		          }
		        },
		        "description": "Optional edits applied to the project after the video is built, in order. Each action runs asynchronously; the response returns one remix action id per action. Recommended for script-to-video: `ENABLE_CAPTIONS` to show and style captions, `CONVERT_IMAGES_TO_VIDEOS` to animate still images into clips, `ADD_TRANSITIONS` to stamp transitions between sections, and `SET_LOGO` to overlay a logo (this workflow has no native caption-style or logo fields). See the [Remix actions](/remix-actions) guide."
		      },
		      {
		        "displayName": "Is Output Temporary",
		        "name": "isOutputTemporary",
		        "type": "boolean",
		        "default": false,
		        "routing": {
		          "send": {
		            "type": "body",
		            "property": "isOutputTemporary"
		          }
		        },
		        "description": "When true, the video's generated OUTPUT files (AI images, video clips, voiceover audio, avatars) are created as temporary: guaranteed available for 24 hours, after which they may be archived and later deleted. This also covers files produced by post-build remix actions (e.g. generated background music, image-to-video conversions). Use this when your integration downloads or re-hosts the results itself and does not need VideoGen to retain them. The project and its metadata are unaffected. Defaults to false."
		      },
		      {
		        "displayName": "Hide From Ui",
		        "name": "hideFromUi",
		        "type": "boolean",
		        "default": false,
		        "routing": {
		          "send": {
		            "type": "body",
		            "property": "hideFromUi"
		          }
		        },
		        "description": "When true, the project is hidden from Home and Projects by default, and generated files are hidden from the Media page. The project and files remain accessible through the API. Defaults to false."
		      },
		      {
		        "displayName": "Export Options",
		        "name": "exportOptions",
		        "type": "json",
		        "default": "{}",
		        "routing": {
		          "send": {
		            "type": "body",
		            "property": "exportOptions",
		            "value": "={{ $value ? JSON.parse($value) : undefined }}"
		          }
		        },
		        "description": "Export settings used when `autoExport` is true. Ignored when `autoExport` is false. Omitted fields use the same defaults as `POST /v1/projects/{projectId}/export`."
		      }
		    ]
		  },
		  {
		    "displayName": "File Id",
		    "name": "fileId",
		    "type": "string",
		    "default": "",
		    "routing": {
		      "send": {
		        "type": "body",
		        "property": "fileId"
		      }
		    },
		    "required": true,
		    "description": "Opaque file id of an uploaded PDF or PowerPoint file (e.g. `vg_file_...`). Upload the file first via `POST /v1/files/upload`.",
		    "displayOptions": {
		      "show": {
		        "resource": [
		          "workflow"
		        ],
		        "operation": [
		          "slideshowToVideo"
		        ]
		      }
		    }
		  },
		  {
		    "displayName": "Additional Fields",
		    "name": "additionalFields",
		    "type": "collection",
		    "placeholder": "Add Field",
		    "default": {},
		    "displayOptions": {
		      "show": {
		        "resource": [
		          "workflow"
		        ],
		        "operation": [
		          "slideshowToVideo"
		        ]
		      }
		    },
		    "options": [
		      {
		        "displayName": "Slide Scripts",
		        "name": "slideScripts",
		        "type": "json",
		        "default": "[]",
		        "routing": {
		          "send": {
		            "type": "body",
		            "property": "slideScripts",
		            "value": "={{ $value ? JSON.parse($value) : undefined }}"
		          }
		        },
		        "description": "Optional per-slide narration, in slide order, applied by index: each slide uses its matching entry, and an empty string makes that slide silent. If you provide fewer entries than slides, the remaining slides are silent; extra entries are ignored. Omit this field entirely to narrate each slide from its speaker notes in the uploaded file. To guarantee no narration on any slide, pass an empty array."
		      },
		      {
		        "displayName": "Aspect Ratio",
		        "name": "aspectRatio",
		        "type": "json",
		        "default": "{}",
		        "routing": {
		          "send": {
		            "type": "body",
		            "property": "aspectRatio",
		            "value": "={{ $value ? JSON.parse($value) : undefined }}"
		          }
		        },
		        "description": "Aspect ratio as a width:height pair (e.g. 16 and 9 for 16:9). Not pixel dimensions."
		      },
		      {
		        "displayName": "Language",
		        "name": "language",
		        "type": "string",
		        "default": "",
		        "routing": {
		          "send": {
		            "type": "body",
		            "property": "language"
		          }
		        },
		        "description": "Output language as a BCP-47 code (e.g. `en`, `es`, `fr`). Defaults to English."
		      },
		      {
		        "displayName": "Voice Id",
		        "name": "voiceId",
		        "type": "string",
		        "default": "",
		        "routing": {
		          "send": {
		            "type": "body",
		            "property": "voiceId"
		          }
		        },
		        "description": "Catalog `displayName` (e.g. `Matilda`) or voice id from `GET /v1/resources/tts-voices` (e.g. `vg_voic_...`). A default voice is used when omitted. Any voice may be used here, including voices where `supportsDirectToolExecution` is false."
		      },
		      {
		        "displayName": "Voice Speed",
		        "name": "voiceSpeed",
		        "type": "number",
		        "default": 0,
		        "routing": {
		          "send": {
		            "type": "body",
		            "property": "voiceSpeed"
		          }
		        },
		        "description": "Speech rate multiplier, between 0.5 (half speed) and 2 (double speed). Defaults to the voice's default speed."
		      },
		      {
		        "displayName": "Actor Entity Id",
		        "name": "actorEntityId",
		        "type": "string",
		        "default": "",
		        "routing": {
		          "send": {
		            "type": "body",
		            "property": "actorEntityId"
		          }
		        },
		        "description": "Recommended. Optional id of a built-in stock actor or an ACTOR entity (e.g. `vg_enti_...`) with an image reference. When set, narration is delivered by that actor avatar. Omit or pass `null` for voiceover without an avatar."
		      },
		      {
		        "displayName": "Avatar Quality",
		        "name": "avatarQuality",
		        "type": "options",
		        "default": "LOW",
		        "routing": {
		          "send": {
		            "type": "body",
		            "property": "avatarQuality"
		          }
		        },
		        "options": [
		          {
		            "name": "LOW",
		            "value": "LOW"
		          },
		          {
		            "name": "STANDARD",
		            "value": "STANDARD"
		          },
		          {
		            "name": "HIGH",
		            "value": "HIGH"
		          },
		          {
		            "name": "MAX",
		            "value": "MAX"
		          }
		        ],
		        "description": "Avatar generation quality tier. Applies when `actorEntityId` is provided. Optional; when omitted, your account's Default AI quality for avatars is used."
		      },
		      {
		        "displayName": "Slideshow Theme Entity Id",
		        "name": "slideshowThemeEntityId",
		        "type": "string",
		        "default": "",
		        "routing": {
		          "send": {
		            "type": "body",
		            "property": "slideshowThemeEntityId"
		          }
		        },
		        "description": "Optional id of a SLIDESHOW_THEME entity (e.g. `vg_enti_...`) whose reference board defines the shared slide design system (fonts, colors, layout) applied to generated or edited slides. Create one via `POST /v1/entities` with `entityType` SLIDESHOW_THEME and attach a reference image or a PDF / PowerPoint. Omit when converting an uploaded deck's original pages into a video; VideoGen derives a theme from those pages in the background so later edits can match the original slides."
		      },
		      {
		        "displayName": "Caption Style",
		        "name": "captionStyle",
		        "type": "json",
		        "default": "{}",
		        "routing": {
		          "send": {
		            "type": "body",
		            "property": "captionStyle",
		            "value": "={{ $value ? JSON.parse($value) : undefined }}"
		          }
		        },
		        "description": "Caption styling. Omit to use the default style with captions shown. Pass an object to override individual style fields (any omitted field uses the default). Pass `null` to hide captions entirely."
		      },
		      {
		        "displayName": "Logo File Id",
		        "name": "logoFileId",
		        "type": "string",
		        "default": "",
		        "routing": {
		          "send": {
		            "type": "body",
		            "property": "logoFileId"
		          }
		        },
		        "description": "Optional file id of an uploaded logo image to overlay on the video (e.g. `vg_file_...`). Upload the image first via `POST /v1/files/upload`. Only image files are accepted."
		      },
		      {
		        "displayName": "Remix Actions",
		        "name": "remixActions",
		        "type": "json",
		        "default": "[]",
		        "routing": {
		          "send": {
		            "type": "body",
		            "property": "remixActions",
		            "value": "={{ $value ? JSON.parse($value) : undefined }}"
		          }
		        },
		        "description": "Optional edits applied to the project after the video is built, in order. Each action runs asynchronously; the response returns one remix action id per action. Captions and a logo are set with the `captionStyle` and `logoFileId` request fields above; recommended remix actions here are `CONVERT_IMAGES_TO_VIDEOS` to animate still images into clips, and `ADD_TRANSITIONS` to stamp transitions between sections and assets. See the [Remix actions](/remix-actions) guide."
		      },
		      {
		        "displayName": "Is Output Temporary",
		        "name": "isOutputTemporary",
		        "type": "boolean",
		        "default": false,
		        "routing": {
		          "send": {
		            "type": "body",
		            "property": "isOutputTemporary"
		          }
		        },
		        "description": "When true, the video's generated OUTPUT files (AI images, video clips, voiceover audio, avatars) are created as temporary: guaranteed available for 24 hours, after which they may be archived and later deleted. This also covers files produced by post-build remix actions (e.g. generated background music, image-to-video conversions). Use this when your integration downloads or re-hosts the results itself and does not need VideoGen to retain them. The project and its metadata are unaffected. Defaults to false."
		      },
		      {
		        "displayName": "Hide From Ui",
		        "name": "hideFromUi",
		        "type": "boolean",
		        "default": false,
		        "routing": {
		          "send": {
		            "type": "body",
		            "property": "hideFromUi"
		          }
		        },
		        "description": "When true, the project is hidden from Home and Projects by default, and generated files are hidden from the Media page. The project and files remain accessible through the API. Defaults to false."
		      },
		      {
		        "displayName": "Export Options",
		        "name": "exportOptions",
		        "type": "json",
		        "default": "{}",
		        "routing": {
		          "send": {
		            "type": "body",
		            "property": "exportOptions",
		            "value": "={{ $value ? JSON.parse($value) : undefined }}"
		          }
		        },
		        "description": "Export settings used when `autoExport` is true. Ignored when `autoExport` is false. Omitted fields use the same defaults as `POST /v1/projects/{projectId}/export`."
		      }
		    ]
		  },
		  {
		    "displayName": "File Id",
		    "name": "fileId",
		    "type": "string",
		    "default": "",
		    "routing": {
		      "send": {
		        "type": "body",
		        "property": "fileId"
		      }
		    },
		    "required": true,
		    "description": "Opaque file id of an uploaded voiceover audio file (e.g. `vg_file_...`). Upload the file first via `POST /v1/files/upload`. Attach a pre-computed transcript at upload time (via the `transcript` field on `POST /v1/files/upload`) to skip re-transcription.",
		    "displayOptions": {
		      "show": {
		        "resource": [
		          "workflow"
		        ],
		        "operation": [
		          "voiceoverToVideo"
		        ]
		      }
		    }
		  },
		  {
		    "displayName": "Visual Style",
		    "name": "visualStyle",
		    "type": "json",
		    "default": "{}",
		    "routing": {
		      "send": {
		        "type": "body",
		        "property": "visualStyle",
		        "value": "={{ $value ? JSON.parse($value) : undefined }}"
		      }
		    },
		    "required": true,
		    "description": "Visual style for the generated b-roll.",
		    "displayOptions": {
		      "show": {
		        "resource": [
		          "workflow"
		        ],
		        "operation": [
		          "voiceoverToVideo"
		        ]
		      }
		    }
		  },
		  {
		    "displayName": "Additional Fields",
		    "name": "additionalFields",
		    "type": "collection",
		    "placeholder": "Add Field",
		    "default": {},
		    "displayOptions": {
		      "show": {
		        "resource": [
		          "workflow"
		        ],
		        "operation": [
		          "voiceoverToVideo"
		        ]
		      }
		    },
		    "options": [
		      {
		        "displayName": "Scenes",
		        "name": "scenes",
		        "type": "json",
		        "default": "[]",
		        "routing": {
		          "send": {
		            "type": "body",
		            "property": "scenes",
		            "value": "={{ $value ? JSON.parse($value) : undefined }}"
		          }
		        },
		        "description": "Optional timed scene descriptions guiding what to show on screen during each absolute time range of the video. Ranges must be sorted by `startSeconds` and non-overlapping. Omit to let the workflow choose visuals automatically."
		      },
		      {
		        "displayName": "Aspect Ratio",
		        "name": "aspectRatio",
		        "type": "json",
		        "default": "{}",
		        "routing": {
		          "send": {
		            "type": "body",
		            "property": "aspectRatio",
		            "value": "={{ $value ? JSON.parse($value) : undefined }}"
		          }
		        },
		        "description": "Aspect ratio as a width:height pair (e.g. 16 and 9 for 16:9). Not pixel dimensions."
		      },
		      {
		        "displayName": "Visual Pacing",
		        "name": "visualPacing",
		        "type": "options",
		        "default": "MEDIUM",
		        "routing": {
		          "send": {
		            "type": "body",
		            "property": "visualPacing"
		          }
		        },
		        "options": [
		          {
		            "name": "FAST",
		            "value": "FAST"
		          },
		          {
		            "name": "MEDIUM",
		            "value": "MEDIUM"
		          },
		          {
		            "name": "SLOW",
		            "value": "SLOW"
		          }
		        ],
		        "description": "How quickly visuals change. FAST shows more, shorter shots; SLOW holds each visual longer. Defaults to MEDIUM."
		      },
		      {
		        "displayName": "Quality",
		        "name": "quality",
		        "type": "options",
		        "default": "LOW",
		        "routing": {
		          "send": {
		            "type": "body",
		            "property": "quality"
		          }
		        },
		        "options": [
		          {
		            "name": "LOW",
		            "value": "LOW"
		          },
		          {
		            "name": "STANDARD",
		            "value": "STANDARD"
		          },
		          {
		            "name": "HIGH",
		            "value": "HIGH"
		          },
		          {
		            "name": "MAX",
		            "value": "MAX"
		          }
		        ],
		        "description": "Image generation quality tier for AI-generated visuals. Optional; when omitted, your account's Default AI quality for images is used (change it at https://app.videogen.io/settings/account). Only applies when `visualStyle.type` is AI_IMAGE; STOCK pulls existing footage and is unaffected."
		      },
		      {
		        "displayName": "Language",
		        "name": "language",
		        "type": "string",
		        "default": "",
		        "routing": {
		          "send": {
		            "type": "body",
		            "property": "language"
		          }
		        },
		        "description": "Output language as a BCP-47 code (e.g. `en`, `es`, `fr`). Defaults to English."
		      },
		      {
		        "displayName": "Actor Entity Id",
		        "name": "actorEntityId",
		        "type": "string",
		        "default": "",
		        "routing": {
		          "send": {
		            "type": "body",
		            "property": "actorEntityId"
		          }
		        },
		        "description": "Recommended. Optional id of a built-in stock actor or an ACTOR entity (e.g. `vg_enti_...`) with an image reference. When set, narration is delivered by that actor avatar. Omit or pass `null` for voiceover without an avatar."
		      },
		      {
		        "displayName": "Avatar Quality",
		        "name": "avatarQuality",
		        "type": "options",
		        "default": "LOW",
		        "routing": {
		          "send": {
		            "type": "body",
		            "property": "avatarQuality"
		          }
		        },
		        "options": [
		          {
		            "name": "LOW",
		            "value": "LOW"
		          },
		          {
		            "name": "STANDARD",
		            "value": "STANDARD"
		          },
		          {
		            "name": "HIGH",
		            "value": "HIGH"
		          },
		          {
		            "name": "MAX",
		            "value": "MAX"
		          }
		        ],
		        "description": "Avatar generation quality tier. Applies when `actorEntityId` is provided. Optional; when omitted, your account's Default AI quality for avatars is used."
		      },
		      {
		        "displayName": "Caption Style",
		        "name": "captionStyle",
		        "type": "json",
		        "default": "{}",
		        "routing": {
		          "send": {
		            "type": "body",
		            "property": "captionStyle",
		            "value": "={{ $value ? JSON.parse($value) : undefined }}"
		          }
		        },
		        "description": "Caption styling. Omit to use the default style with captions shown. Pass an object to override individual style fields (any omitted field uses the default). Pass `null` to hide captions entirely."
		      },
		      {
		        "displayName": "Logo File Id",
		        "name": "logoFileId",
		        "type": "string",
		        "default": "",
		        "routing": {
		          "send": {
		            "type": "body",
		            "property": "logoFileId"
		          }
		        },
		        "description": "Optional file id of an uploaded logo image to overlay on the video (e.g. `vg_file_...`). Upload the image first via `POST /v1/files/upload`. Only image files are accepted."
		      },
		      {
		        "displayName": "Workflow Agent Context",
		        "name": "workflowAgentContext",
		        "type": "string",
		        "default": "",
		        "routing": {
		          "send": {
		            "type": "body",
		            "property": "workflowAgentContext"
		          }
		        },
		        "description": "Optional production notes for the AI that builds the video — visual direction for how to illustrate the voiceover (e.g. on-screen code or text to display, specific b-roll to feature, or scene-by-scene staging). Never spoken; does not change the uploaded voiceover audio or its transcript."
		      },
		      {
		        "displayName": "Remix Actions",
		        "name": "remixActions",
		        "type": "json",
		        "default": "[]",
		        "routing": {
		          "send": {
		            "type": "body",
		            "property": "remixActions",
		            "value": "={{ $value ? JSON.parse($value) : undefined }}"
		          }
		        },
		        "description": "Optional edits applied to the project after the video is built, in order. Each action runs asynchronously; the response returns one remix action id per action. Captions and a logo are set with the `captionStyle` and `logoFileId` request fields above; recommended remix actions here are `CONVERT_IMAGES_TO_VIDEOS` to animate still images into clips, and `ADD_TRANSITIONS` to stamp transitions between sections and assets. See the [Remix actions](/remix-actions) guide."
		      },
		      {
		        "displayName": "Is Output Temporary",
		        "name": "isOutputTemporary",
		        "type": "boolean",
		        "default": false,
		        "routing": {
		          "send": {
		            "type": "body",
		            "property": "isOutputTemporary"
		          }
		        },
		        "description": "When true, the video's generated OUTPUT files (AI images, video clips, voiceover audio, avatars) are created as temporary: guaranteed available for 24 hours, after which they may be archived and later deleted. This also covers files produced by post-build remix actions (e.g. generated background music, image-to-video conversions). Use this when your integration downloads or re-hosts the results itself and does not need VideoGen to retain them. The project and its metadata are unaffected. Defaults to false."
		      },
		      {
		        "displayName": "Hide From Ui",
		        "name": "hideFromUi",
		        "type": "boolean",
		        "default": false,
		        "routing": {
		          "send": {
		            "type": "body",
		            "property": "hideFromUi"
		          }
		        },
		        "description": "When true, the project is hidden from Home and Projects by default, and generated files are hidden from the Media page. The project and files remain accessible through the API. Defaults to false."
		      },
		      {
		        "displayName": "Export Options",
		        "name": "exportOptions",
		        "type": "json",
		        "default": "{}",
		        "routing": {
		          "send": {
		            "type": "body",
		            "property": "exportOptions",
		            "value": "={{ $value ? JSON.parse($value) : undefined }}"
		          }
		        },
		        "description": "Export settings used when `autoExport` is true. Ignored when `autoExport` is false. Omitted fields use the same defaults as `POST /v1/projects/{projectId}/export`."
		      }
		    ]
		  }
		],
	};

	async execute(this: IExecuteFunctions): Promise<INodeExecutionData[][]> {
		const items = this.getInputData();
		const returnData: INodeExecutionData[] = [];
		const authentication = this.getNodeParameter("authentication", 0) as string;
		const credentialType = credentialTypeFor(authentication);

		for (let i = 0; i < items.length; i++) {
			const operation = this.getNodeParameter("operation", i) as string;
			const spec = WORKFLOW_STARTS[operation];
			if (spec == null) {
				throw new NodeApiError(this.getNode(), { message: `Unsupported operation: ${operation}` });
			}

			const body: IDataObject = { autoExport: true };
			for (const key of spec.requiredBodyKeys) {
				body[key] = parseMaybeJson(this.getNodeParameter(key, i), key, spec.jsonKeys) as IDataObject[string];
			}
			const additional = this.getNodeParameter("additionalFields", i, {}) as IDataObject;
			for (const [key, value] of Object.entries(additional)) {
				body[key] = parseMaybeJson(value, key, spec.jsonKeys) as IDataObject[string];
			}

			const started = (await this.helpers.httpRequestWithAuthentication.call(this, credentialType, {
				method: spec.method,
				url: `${BASE_URL}${spec.path}`,
				body,
				json: true,
			})) as IDataObject;

			const workflowRunId = started.workflowRunId;
			if (typeof workflowRunId !== "string" || workflowRunId === "") {
				throw new NodeApiError(this.getNode(), { message: "Workflow start did not return a run id" });
			}

			const run = await pollWorkflowRun(this, credentialType, workflowRunId);
			returnData.push({ json: run });
		}

		return [returnData];
	}
}
